parameters:
#    amp_pdf_crowd.example.class: Amp\PDFCrowdBundle\Example

services:
#    amp_pdf_crowd.example:
#        class: %amp_pdf_crowd.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
