parameters:
    amp_pdf_crowd.api.class: Amp\PDFCrowdBundle\Lib\PDFCrowd

services:
    amp_pdf_crowd.api:
        class: %amp_pdf_crowd.api.class%
        arguments: [ %amp_pdf_crowd.username%, %amp_pdf_crowd.apikey% ]
